import { EItemType } from '../../../user/IUserData';
export var EItemId = {
  Shuffle: "shuffle",
  Hint: "hint",
  Revert: "revert",
  Revive: "revive",
  Magnet: "magnet"
};
export enum ResId {
  emYogaCardId = 42,
  emBombCardId = 43,
  emRankId = 50,
}
export enum MjCardId {
  emFlowCardId = 35,
  emSeasonCardId = 36,
  emYogaCardId = 37,
  emBombCardId = 38,
  emTravelEgyptId = 39,
  emRankId = 50,
  emFlowCardIdMei = 54,
  emFlowCardIdLan = 55,
  emFlowCardIdZhu = 56,
  emFlowCardIdJu = 57,
  emSeasonCardIdChun = 58,
  emSeasonCardIdXia = 59,
  emSeasonCardIdQiu = 60,
  emSeasonCardIdDong = 61,
}
export enum LevelTargetType {
  AllKill = 0,
  KillCollectCard = 1,
}
export var MjGameType = {
  None: "None",
  Normal: "Normal",
  Travel: "Travel",
  DailyChallenge: "DailyChallenge",
  Classic: "Classic",
  Tile2Normal: "Tile2Normal"
};
export enum JourneyType {
  Yoga = 1,
  Flip = 2,
  Color = 3,
}
export var EAudioDefine = {
  Bgm: "m_bgm",
  BtnClick: "m_click",
  Birth: "m_birth",
  Check1: "m_touch",
  Hint: "m_notice",
  Uncheck: "m_put",
  FullCombo: "m_perfect",
  Bonus: "m_bonus",
  Match: "m_streak",
  Refresh: "m_refresh",
  Wrong: "m_wrong",
  Good: "m_good",
  Great: "m_great",
  Excellent: "m_excellent",
  Amazing: "m_amazing",
  Unbelievable: "m_unbelievable",
  Hammer: "m_hammer",
  Win: "m_win",
  WinCharge: "m_charge",
  Box: "m_box",
  Applause: "m_applause",
  Drag: "m_drag",
  TaskBanner: "m_blank",
  TaskComplete: "m_kind",
  Goals: "m_goals",
  CollectionShow: "m_collection",
  CollectionSpecial: "m_collect",
  SpecialTouch: "m_special",
  Special2Streak: "m_special2",
  Blank: "m_blank",
  Targetfly1: "m_targetfly1",
  Targetfly2: "m_targetfly2",
  Targetfly3: "m_targetfly3",
  Ranking1: "m_ranking1",
  Ranking2: "m_ranking2",
  Box3Show: "m_box3",
  Box2Open: "m_box2",
  Button1: "m_button1",
  BlankCom: "m_blank",
  Charge: "m_charge",
  Collect2: "m_collect2",
  ItemStart: "m_shinning",
  ItemMove: "m_rank",
  ItemEnd: "m_score",
  BonusEgyptA: "m_bonus_egypt_A",
  TravelTags: "m_tags",
  TravelBlankCommon: "m_blank",
  TravelButton1: "m_button1",
  TravelCollect: "m_collect1",
  RefreshRoll: "m_refresh_roll"
};
export enum EAudioID {
  Bgm = 1,
  BtnClick = 2,
  Birth = 3,
  Check1 = 4,
  Hint = 5,
  Uncheck = 6,
  FullCombo = 7,
  Bonus = 8,
  Match = 9,
  Refresh = 10,
  Wrong = 11,
  Good = 12,
  Great = 13,
  Excellent = 14,
  Amazing = 15,
  Unbelievable = 16,
  Hammer = 17,
  Win = 18,
  WinCharge = 19,
  Box = 20,
  Applause = 21,
  Drag = 22,
  TaskBanner = 23,
  TaskComplete = 24,
  Goals = 25,
  CollectionShow = 26,
  CollectionSpecial = 27,
  SpecialTouch = 28,
  Special2Streak = 29,
  Blank = 30,
  Targetfly1 = 31,
  Targetfly2 = 32,
  Targetfly3 = 33,
  Ranking1 = 39,
  Ranking2 = 40,
  Box3Show = 41,
  Box2Open = 42,
  Button1 = 43,
  BlankCom = 44,
  Charge = 45,
  Collect2 = 46,
  ItemStart = 47,
  ItemMove = 48,
  ItemEnd = 49,
  BonusEgyptA = 50,
  TravelTags = 51,
  TravelBlankCommon = 52,
  TravelButton1 = 53,
  TravelCollect = 54,
  GoodMan = 57,
  GreatMan = 58,
  ExcellentMan = 59,
  AmazingMan = 60,
  UnbelievableMan = 61,
  HardLevelBanner = 68,
  ClassicBatch = 69,
  ClassicWin = 70,
  ClassicLose = 71,
  ClassicScoreRoll = 72,
  ClassicRevive = 73,
  ClassicBreakRecord = 74,
  EnterHall = 86,
  EnterTravel = 87,
  RankClearCol1 = 94,
  RankClearCol2 = 95,
  RankClearTouch = 96,
  Tile2Fail = 97,
  Revert = 98,
  AllClear = 99,
  Tile2Touch = 100,
  Tile2Overturn = 101,
  Tile2Touch2 = 102,
  SkinUnlock = 103,
  Tile2Lucky = 104,
  Tile2Perfect = 106,
  RefreshRoll = 105,
  AllClearGather = 107,
  MagnetMerge = 108,
  Tile2Fail3Slot = 109,
  Tile2Fit = 110,
}
(EItemName = {})[EItemId.Shuffle] = "重洗牌";
EItemName[EItemId.Hint] = "提示";
EItemName[EItemId.Revert] = "撤回";
EItemName[EItemId.Revive] = "复活";
EItemName[EItemId.Magnet] = "磁铁";
export var EItemName = EItemName;
(ItemType2Id = {})[EItemType.Shuffle] = EItemId.Shuffle;
ItemType2Id[EItemType.Hint] = EItemId.Hint;
ItemType2Id[EItemType.Undo] = EItemId.Revert;
export var ItemType2Id = ItemType2Id;
export var EGetItemReasonId = {
  SystemGift: "系统赠送",
  AdReward: "广告",
  DailyTask: "每日任务奖励",
  DailyChallengeAd: "每日挑战",
  Journey: "旅行活动奖励",
  LevelBox: "主关卡宝箱奖励",
  LevelBoxAd: "主关卡宝箱奖励_看广告翻倍",
  DailyTaskAd: "每日任务奖励_看广告翻倍",
  JourneyAd: "旅行活动奖励_看广告翻倍",
  LeaderBoard: "排行榜活动奖励",
  LeaderBoardAd: "排行榜活动奖励_看广告翻倍",
  AgeSurvey: "年龄调研奖励",
  AgeSurveyAd: "年龄调研奖励_看广告翻倍",
  WinStreakReward: "连胜奖励",
  DailySign: "每日签到奖励",
  DailySignAd: "每日签到奖励_看广告翻倍",
  DailySignClassic: "经典每日登录",
  DailySignSimple: "简易每日登录"
};
export var ERedDotPosition = {
  Left: "left",
  Right: "right",
  Special: "special"
};
export var ERedDotType = {
  Setting: "setting",
  Journey: "journey",
  DailyChallenge: "dailyChallenge",
  Rank: "rank",
  Task: "task",
  DailySignClassic: "dailySignClassic",
  Valentine: "valentine"
};
export var EMergeType = {
  Normal: "normal",
  Bomb: "bomb",
  FullCombo: "fullCombo",
  Duoxiao: "duoxiao",
  Daxiao: "daxiao"
};
export var ETile2SlotType = {
  Slot3: "Slot3",
  Slot4: "Slot4"
};