import { BehaviorsMapping } from './mapping/BehaviorsMapping';
import { BeforeWinBehavior } from './BeforeWinBehavior';
import { BlockInputBehavior } from './base/BlockInputBehavior';
import { BombBehavior } from './base/BombBehavior';
import { CancelBehavior } from './base/CancelBehavior';
import CleanViewBehavior from './base/CleanViewBehavior';
import { CollectFlyBehavior } from './base/CollectFlyBehavior';
import { GoalAchieveBehavior } from './base/GoalAchieveBehavior';
import { InitCollectTargetBehavior } from './base/InitCollectTargetBehavior';
import { UpdateCollectTargetBehavior } from './base/UpdateCollectTargetBehavior';
import { ClearBehavior } from './base/ClearBehavior';
import { ClearEffectBehavior } from './base/ClearEffectBehavior';
import { ClickShowLockBehavior } from './base/ClickShowLockBehavior';
import { DailyChallengeDateBehavior } from './base/DailyChallengeDateBehavior';
import { BeforeDailyChallengeWinBehavior } from './BeforeDailyChallengeWinBehavior';
import { DailyChallengeWinBehavior } from './base/DailyChallengeWinBehavior';
import EmptyBehavior from './base/EmptyBehavior';
import { EnterAnimationBehavior } from './base/EnterAnimationBehavior';
import { FailBehavior } from './base/FailBehavior';
import { FullComboBehavior } from './base/FullComboBehavior';
import { HitTipsBehavior } from './base/HitTipsBehavior';
import { InitViewBehavior } from './base/InitViewBehavior';
import MotivationalWordsBehavior from './base/MotivationalWordsBehavior';
import MotivationalWordsEffectBehavior from './base/MotivationalWordsEffectBehavior';
import { MoveBehavior } from './base/MoveBehavior';
import { RewardComboBehavior } from './base/RewardComboBehavior';
import { ScoreFloatBehavior } from './base/ScoreFloatBehavior';
import { SelectBehavior } from './base/SelectBehavior';
import { SelectLockBehavior } from './base/SelectLockBehavior';
import { ShowLockMaskBehavior } from './base/ShowLockMaskBehavior';
import { ShuffleBehavior } from './base/ShuffleBehavior';
import { SpiralShuffleBehavior } from './base/SpiralShuffleBehavior';
import { StackShuffleBehavior } from './base/StackShuffleBehavior';
import { SkipAutoMergeBehavior } from './base/SkipAutoMergeBehavior';
import { StartAutoMergeBehavior } from './base/StartAutoMergeBehavior';
import { UnSelectBehavior } from './base/UnSelectBehavior';
import { UpdateComboBehavior } from './base/UpdateComboBehavior';
import UpdateHitTipsPropBehavior from './base/UpdateHitTipsPropBehavior';
import { UpdateLevelBehavior } from './base/UpdateLevelBehavior';
import { UpdateMatchNumBehavior } from './base/UpdateMatchNumBehavior';
import { UpdateScoreBehavior } from './base/UpdateScoreBehavior';
import UpdateShufflePropBehavior from './base/UpdateShufflePropBehavior';
import { WinBehavior } from './base/WinBehavior';
import YogaCardBehavior from './base/YogaCardBehavior';
import { TravelWinBehavior } from './base/TravelWinBehavior';
import { DaxiaoClearEffectBehavior } from './base/DaxiaoClearEffectBehavior';
import { DaxiaoClearTipBehavior } from './base/DaxiaoClearTipBehavior';
import { DuoxiaoComboBehavior } from './base/DuoxiaoComboBehavior';
import { Tile2DuoxiaoComboBehavior } from './base/Tile2DuoxiaoComboBehavior';
import { BlockInputRefBehavior } from './base/BlockInputRefBehavior';
import { EnterAnimationFinishBehavior } from './base/EnterAnimationFinishBehavior';
import { StartInitBehavior } from './base/StartInitBehavior';
import { Match1PropTipsBehavior } from './base/Match1PropTipsBehavior';
import { AddPropOff3hBehavior } from './AddPropOff3hBehavior';
import { InitNextLevelBehavior } from './base/InitNextLevelBehavior';
import { AddLevelEnterAniBehavior } from './AddLevelEnterAniBehavior';
import { AddLevelUnlockBehavior } from './AddLevelUnlockBehavior';
import { PushBatchInfoBehavior } from './base/PushBatchInfoBehavior';
import { ClassicFailBehavior } from './base/ClassicFailBehavior';
import { ChangeBatchBehavior } from './base/ChangeBatchBehavior';
import { BlockInputRefWithParamBehavior } from './base/BlockInputRefWithParamBehavior';
import { ClassicReviveBehavior } from './base/ClassicReviveBehavior';
import { ChangeBatchAnimBehavior } from './base/ChangeBatchAnimBehavior';
import { AddLevelFinishBehavior } from './AddLevelFinishBehavior';
import { AddLevelDropBehavior } from './AddLevelDropBehavior';
import { AddLevelDropAniBehavior } from './AddLevelDropAniBehavior';
import { ClassicBeforeFailBehavior } from './base/ClassicBeforeFailBehavior';
import { Tile2InitSlotBarBehavior } from './base/Tile2InitSlotBarBehavior';
import { Tile2InitBottomBehavior } from './base/Tile2InitBottomBehavior';
import { Tile2InitTopBehavior } from './base/Tile2InitTopBehavior';
import { Tile2UpdateSlotBarBehavior } from './base/Tile2UpdateSlotBarBehavior';
import { Tile2ClearBehavior } from './base/Tile2ClearBehavior';
import { Tile2ClearEffectBehavior } from './base/Tile2ClearEffectBehavior';
import { Tile2ResetMoveBehavior } from './base/Tile2ResetMoveBehavior';
import { Tile2MoveBehavior } from './base/Tile2MoveBehavior';
import { Tile2FailBehavior } from './base/Tile2FailBehavior';
import { Tile2BeforeFailBehavior } from './base/Tile2BeforeFailBehavior';
import { Tile2ReviveBehavior } from './base/Tile2ReviveBehavior';
import { Tile2BeforeWinBehavior } from './base/Tile2BeforeWinBehavior';
import { Tile2WinBehavior } from './base/Tile2WinBehavior';
import { Tile2NotEnoughItemsBehavior } from './base/Tile2NotEnoughItemsBehavior';
import { Tile2UpdateItemBehavior } from './base/Tile2UpdateItemBehavior';
import { Tile2ShuffleBehavior } from './base/Tile2ShuffleBehavior';
import { Tile2HitTipsBehavior } from './base/Tile2HitTipsBehavior';
import { Tile2UpdateHitTipsItemBehavior } from './base/Tile2UpdateHitTipsItemBehavior';
import { Tile2RevertBehavior } from './base/Tile2RevertBehavior';
import { Tile2UpdateRevertItemBehavior } from './base/Tile2UpdateRevertItemBehavior';
import { Tile2ScoreFloatBehavior } from './base/Tile2ScoreFloatBehavior';
import { Tile2UpdateScoreBehavior } from './base/Tile2UpdateScoreBehavior';
import { Tile2UpdateComboBehavior } from './base/Tile2UpdateComboBehavior';
import { Tile2DianZanBehavior } from './base/Tile2DianZanBehavior';
import { Tile2RollCardBehavior } from './base/Tile2RollCardBehavior';
import { Tile2ShuffleVibrateBehavior } from './base/Tile2ShuffleVibrateBehavior';
import { Tile2HitTipsVibrateBehavior } from './base/Tile2HitTipsVibrateBehavior';
import { Tile2RevertVibrateBehavior } from './base/Tile2RevertVibrateBehavior';
import { Tile2NoHintTipsBehavior } from './base/Tile2NoHintTipsBehavior';
import { Tile2ScreenEdgeEffectBehavior } from './base/Tile2ScreenEdgeEffectBehavior';
import { Tile2ScreenTopEffectBehavior } from './base/Tile2ScreenTopEffectBehavior';
import { Tile2SlotAdvanceBehavior } from './base/Tile2SlotAdvanceBehavior';
import { Tile2RestartBehavior } from './base/Tile2RestartBehavior';
import { Tile2CheerBehavior } from './base/Tile2CheerBehavior';
import { Tile2NoValidTilesBehavior } from './base/Tile2NoValidTilesBehavior';
import { AllClearBehavior } from './AllClearBehavior';
import { Tile2StartAutoMergeBehavior } from './base/Tile2StartAutoMergeBehavior';
import { Tile2MagnetBehavior } from './base/Tile2MagnetBehavior';
import { Tile2MagnetHideBehavior } from './base/Tile2MagnetHideBehavior';
import { Tile2MagnetMergeBehavior } from './base/Tile2MagnetMergeBehavior';
import { Tile2RemoveHitTipsBehavior } from './base/Tile2RemoveHitTipsBehavior';
import { Tile2LuckyBehavior } from './base/Tile2LuckyBehavior';
import { Tile2PerfectBehavior } from './base/Tile2PerfectBehavior';
import { Tile2TouchStartBehavior } from './base/Tile2TouchStartBehavior';
import { Tile2NormalBackBehavior } from './base/Tile2NormalBackBehavior';
import { Tile2SlotCardNumChangeBehavior } from './base/Tile2SlotCardNumChangeBehavior';
export class BehaviorFactory {
  static _behaviorMap = {};
  static _hasInit = false;
  static getBehavior(e) {
    return this._behaviorMap[e];
  }
  static registerBehavior(e, t) {
    this._behaviorMap[e] = t;
  }
  static init() {
    if (!this._hasInit) {
      this._hasInit = true;
      this.registerBehavior(BehaviorsMapping.EnterAnimation, EnterAnimationBehavior);
      this.registerBehavior(BehaviorsMapping.Select, SelectBehavior);
      this.registerBehavior(BehaviorsMapping.UnSelect, UnSelectBehavior);
      this.registerBehavior(BehaviorsMapping.SelectLock, SelectLockBehavior);
      this.registerBehavior(BehaviorsMapping.Move, MoveBehavior);
      this.registerBehavior(BehaviorsMapping.Clear, ClearBehavior);
      this.registerBehavior(BehaviorsMapping.BeforeWin, BeforeWinBehavior);
      this.registerBehavior(BehaviorsMapping.End, WinBehavior);
      this.registerBehavior(BehaviorsMapping.Fail, FailBehavior);
      this.registerBehavior(BehaviorsMapping.InitView, InitViewBehavior);
      this.registerBehavior(BehaviorsMapping.UpdateScore, UpdateScoreBehavior);
      this.registerBehavior(BehaviorsMapping.ScoreFloat, ScoreFloatBehavior);
      this.registerBehavior(BehaviorsMapping.UpdateCombo, UpdateComboBehavior);
      this.registerBehavior(BehaviorsMapping.FullCombo, FullComboBehavior);
      this.registerBehavior(BehaviorsMapping.AllClear, AllClearBehavior);
      this.registerBehavior(BehaviorsMapping.ClearEffect, ClearEffectBehavior);
      this.registerBehavior(BehaviorsMapping.UpdateMatchNum, UpdateMatchNumBehavior);
      this.registerBehavior(BehaviorsMapping.UpdateLevel, UpdateLevelBehavior);
      this.registerBehavior(BehaviorsMapping.HitTips, HitTipsBehavior);
      this.registerBehavior(BehaviorsMapping.Shuffle, ShuffleBehavior);
      this.registerBehavior(BehaviorsMapping.SpiralShuffle, SpiralShuffleBehavior);
      this.registerBehavior(BehaviorsMapping.StackShuffle, StackShuffleBehavior);
      this.registerBehavior(BehaviorsMapping.TouchCancel, CancelBehavior);
      this.registerBehavior(BehaviorsMapping.Empty, EmptyBehavior);
      this.registerBehavior(BehaviorsMapping.UpdateHitTipsProp, UpdateHitTipsPropBehavior);
      this.registerBehavior(BehaviorsMapping.UpdateShuffleProp, UpdateShufflePropBehavior);
      this.registerBehavior(BehaviorsMapping.MotivationalWords, MotivationalWordsBehavior);
      this.registerBehavior(BehaviorsMapping.MotivationalWordsEffect, MotivationalWordsEffectBehavior);
      this.registerBehavior(BehaviorsMapping.ClickShowLock, ClickShowLockBehavior);
      this.registerBehavior(BehaviorsMapping.ShowLockMask, ShowLockMaskBehavior);
      this.registerBehavior(BehaviorsMapping.RewardCombo, RewardComboBehavior);
      this.registerBehavior(BehaviorsMapping.Bomb, BombBehavior);
      this.registerBehavior(BehaviorsMapping.CleanView, CleanViewBehavior);
      this.registerBehavior(BehaviorsMapping.StartAutoMerge, StartAutoMergeBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2StartAutoMerge, Tile2StartAutoMergeBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2Magnet, Tile2MagnetBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2MagnetMerge, Tile2MagnetMergeBehavior);
      this.registerBehavior(BehaviorsMapping.SkipAutoMerge, SkipAutoMergeBehavior);
      this.registerBehavior(BehaviorsMapping.DailyChallengeDate, DailyChallengeDateBehavior);
      this.registerBehavior(BehaviorsMapping.BeforeDailyChallengeEnd, BeforeDailyChallengeWinBehavior);
      this.registerBehavior(BehaviorsMapping.YogaCard, YogaCardBehavior);
      this.registerBehavior(BehaviorsMapping.DailyChallengeEnd, DailyChallengeWinBehavior);
      this.registerBehavior(BehaviorsMapping.InitCollectTarget, InitCollectTargetBehavior);
      this.registerBehavior(BehaviorsMapping.UpdateCollectTarget, UpdateCollectTargetBehavior);
      this.registerBehavior(BehaviorsMapping.CollectFly, CollectFlyBehavior);
      this.registerBehavior(BehaviorsMapping.GoalAchieve, GoalAchieveBehavior);
      this.registerBehavior(BehaviorsMapping.TravelEnd, TravelWinBehavior);
      this.registerBehavior(BehaviorsMapping.BlockInput, BlockInputBehavior);
      this.registerBehavior(BehaviorsMapping.DaxiaoClearEffectEffect, DaxiaoClearEffectBehavior);
      this.registerBehavior(BehaviorsMapping.DaxiaoClearTipEffect, DaxiaoClearTipBehavior);
      this.registerBehavior(BehaviorsMapping.DuoxiaoCombo, DuoxiaoComboBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2DuoxiaoCombo, Tile2DuoxiaoComboBehavior);
      this.registerBehavior(BehaviorsMapping.BlockInputRef, BlockInputRefBehavior);
      this.registerBehavior(BehaviorsMapping.EnterAnimationFinish, EnterAnimationFinishBehavior);
      this.registerBehavior(BehaviorsMapping.StartInit, StartInitBehavior);
      this.registerBehavior(BehaviorsMapping.Match1PropTips, Match1PropTipsBehavior);
      this.registerBehavior(BehaviorsMapping.AddPropOff3h, AddPropOff3hBehavior);
      this.registerBehavior(BehaviorsMapping.InitNextLevel, InitNextLevelBehavior);
      this.registerBehavior(BehaviorsMapping.AddLevelEnterAni, AddLevelEnterAniBehavior);
      this.registerBehavior(BehaviorsMapping.AddLevelUnlock, AddLevelUnlockBehavior);
      this.registerBehavior(BehaviorsMapping.PushBatchInfo, PushBatchInfoBehavior);
      this.registerBehavior(BehaviorsMapping.ClassicFail, ClassicFailBehavior);
      this.registerBehavior(BehaviorsMapping.ChangeBatch, ChangeBatchBehavior);
      this.registerBehavior(BehaviorsMapping.BlockInputRefWithParam, BlockInputRefWithParamBehavior);
      this.registerBehavior(BehaviorsMapping.ClassicRevive, ClassicReviveBehavior);
      this.registerBehavior(BehaviorsMapping.ChangeBatchAnim, ChangeBatchAnimBehavior);
      this.registerBehavior(BehaviorsMapping.AddLevelFinish, AddLevelFinishBehavior);
      this.registerBehavior(BehaviorsMapping.AddLevelDrop, AddLevelDropBehavior);
      this.registerBehavior(BehaviorsMapping.AddLevelDropAni, AddLevelDropAniBehavior);
      this.registerBehavior(BehaviorsMapping.ClassicBeforeFail, ClassicBeforeFailBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2InitSlotBar, Tile2InitSlotBarBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2InitBottom, Tile2InitBottomBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2InitTop, Tile2InitTopBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2UpdateSlotBar, Tile2UpdateSlotBarBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2ResetMove, Tile2ResetMoveBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2RollCard, Tile2RollCardBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2Move, Tile2MoveBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2Clear, Tile2ClearBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2ClearEffect, Tile2ClearEffectBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2Fail, Tile2FailBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2BeforeFail, Tile2BeforeFailBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2Revive, Tile2ReviveBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2BeforeEnd, Tile2BeforeWinBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2End, Tile2WinBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2NotEnoughItems, Tile2NotEnoughItemsBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2UpdateItem, Tile2UpdateItemBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2Shuffle, Tile2ShuffleBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2HitTips, Tile2HitTipsBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2UpdateHitTipsItem, Tile2UpdateHitTipsItemBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2Revert, Tile2RevertBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2UpdateRevertItem, Tile2UpdateRevertItemBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2ScoreFloat, Tile2ScoreFloatBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2UpdateScore, Tile2UpdateScoreBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2UpdateCombo, Tile2UpdateComboBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2DianZan, Tile2DianZanBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2Magnet, Tile2MagnetBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2MagnetHide, Tile2MagnetHideBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2ShuffleVibrate, Tile2ShuffleVibrateBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2HitTipsVibrate, Tile2HitTipsVibrateBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2RevertVibrate, Tile2RevertVibrateBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2TouchStart, Tile2TouchStartBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2NoHintTips, Tile2NoHintTipsBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2ScreenEdgeEffect, Tile2ScreenEdgeEffectBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2ScreenTopEffect, Tile2ScreenTopEffectBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2SlotAdvance, Tile2SlotAdvanceBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2Restart, Tile2RestartBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2Cheer, Tile2CheerBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2NoValidTiles, Tile2NoValidTilesBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2RemoveHitTips, Tile2RemoveHitTipsBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2Lucky, Tile2LuckyBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2Perfect, Tile2PerfectBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2NormalBack, Tile2NormalBackBehavior);
      this.registerBehavior(BehaviorsMapping.Tile2SlotCardNumChange, Tile2SlotCardNumChangeBehavior);
    }
  }
}