export var EVT_MSG_KEY_SIMULATOR_DISPLAY = "EVT_MSG_KEY_SIMULATOR_DISPLAY";
export var EVT_MSG_KEY_SIMULATOR_INPUT = "EVT_MSG_KEY_SIMULATOR_INPUT";
export var EVT_MSG_KEY_SIMULATOR_NEXTLEVEL = "EVT_MSG_KEY_SIMULATOR_NEXTLEVEL";
export var EVT_MSG_KEY_SIMULATOR_DISPLAY_VIDEO = "EVT_MSG_KEY_SIMULATOR_DISPLAY_VIDEO";